// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS4uoCzU7LWKrJpz5-ZWIVoCnyQVczKNg',
    appId: '1:82352854112:web:82c75c80da1d5343b85f05',
    messagingSenderId: '82352854112',
    projectId: 'mapvlog-1f06d',
    authDomain: 'pinflick.web.app',
    storageBucket: 'mapvlog-1f06d.firebasestorage.app',
    measurementId: 'G-FZVNKDGDQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuvmIsDP5CA6-IDKQ6ht_iG6FjGjL_4ao',
    appId: '1:82352854112:android:2e0c8a88b8b44e16b85f05',
    messagingSenderId: '82352854112',
    projectId: 'mapvlog-1f06d',
    storageBucket: 'mapvlog-1f06d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWGVczJFa6X43hd-F311rfyU4W0Z3MBw',
    appId: '1:82352854112:ios:f58d293f1e52dbf8b85f05',
    messagingSenderId: '82352854112',
    projectId: 'mapvlog-1f06d',
    storageBucket: 'mapvlog-1f06d.firebasestorage.app',
    iosClientId: '82352854112-m9a67bor657b3ed10lsp96i815d9t87u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapvlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvWGVczJFa6X43hd-F311rfyU4W0Z3MBw',
    appId: '1:82352854112:ios:f58d293f1e52dbf8b85f05',
    messagingSenderId: '82352854112',
    projectId: 'mapvlog-1f06d',
    storageBucket: 'mapvlog-1f06d.firebasestorage.app',
    iosClientId: '82352854112-m9a67bor657b3ed10lsp96i815d9t87u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapvlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS4uoCzU7LWKrJpz5-ZWIVoCnyQVczKNg',
    appId: '1:82352854112:web:4c40cd634ac43df2b85f05',
    messagingSenderId: '82352854112',
    projectId: 'mapvlog-1f06d',
    authDomain: 'pinflick.web.app',
    storageBucket: 'mapvlog-1f06d.firebasestorage.app',
    measurementId: 'G-NSR2J02GJC',
  );
}
